from collections import namedtuple

class Pokedex(object):
    def __init__(self):
        pokeTuple = namedtuple('pokeTuple', ['name', 'id', 'type'])
        self.me = [
            pokeTuple(name='Bulbasaur', id=1, type=['grass', 'poison']), 
            pokeTuple(name='Ivysaur', id=2, type=['grass', 'poison']), 
            pokeTuple(name='Venusaur', id=3, type=['grass', 'poison']), 
            pokeTuple(name='Charmander', id=4, type=['fire']), 
            pokeTuple(name='Charmeleon', id=5, type=['fire']), 
            pokeTuple(name='Charizard', id=6, type=['fire', 'flying']), 
            pokeTuple(name='Squirtle', id=7, type=['water']), 
            pokeTuple(name='Wartortle', id=8, type=['water']), 
            pokeTuple(name='Blastoise', id=9, type=['water']), 
            pokeTuple(name='Caterpie', id=10, type=['bug']), 
            pokeTuple(name='Metapod', id=11, type=['bug']), 
            pokeTuple(name='Butterfree', id=12, type=['bug', 'flying']), 
            pokeTuple(name='Weedle', id=13, type=['bug', 'poison']), 
            pokeTuple(name='Kakuna', id=14, type=['bug', 'poison']), 
            pokeTuple(name='Beedrill', id=15, type=['bug', 'poison']), 
            pokeTuple(name='Pidgey', id=16, type=['normal', 'flying']), 
            pokeTuple(name='Pidgeotto', id=17, type=['normal', 'flying']), 
            pokeTuple(name='Pidgeot', id=18, type=['normal', 'flying']), 
            pokeTuple(name='Rattata', id=19, type=['normal']), 
            pokeTuple(name='Raticate', id=20, type=['normal']), 
            pokeTuple(name='Spearow', id=21, type=['normal', 'flying']), 
            pokeTuple(name='Fearow', id=22, type=['normal', 'flying']), 
            pokeTuple(name='Ekans', id=23, type=['poison']), 
            pokeTuple(name='Arbok', id=24, type=['poison']), 
            pokeTuple(name='Pikachu', id=25, type=['electric']), 
            pokeTuple(name='Raichu', id=26, type=['electric']), 
            pokeTuple(name='Sandshrew', id=27, type=['ground']), 
            pokeTuple(name='Sandslash', id=28, type=['ground']), 
            pokeTuple(name='Nidorina', id=30, type=['poison']), 
            pokeTuple(name='Nidoqueen', id=31, type=['poison', 'ground']), 
            pokeTuple(name='Nidorino', id=33, type=['poison']), 
            pokeTuple(name='Nidoking', id=34, type=['poison', 'ground']), 
            pokeTuple(name='Clefairy', id=35, type=['fairy']), 
            pokeTuple(name='Clefable', id=36, type=['fairy']), 
            pokeTuple(name='Vulpix', id=37, type=['fire']), 
            pokeTuple(name='Ninetales', id=38, type=['fire']), 
            pokeTuple(name='Jigglypuff', id=39, type=['normal', 'fairy']), 
            pokeTuple(name='Wigglytuff', id=40, type=['normal', 'fairy']), 
            pokeTuple(name='Zubat', id=41, type=['poison', 'flying']), 
            pokeTuple(name='Golbat', id=42, type=['poison', 'flying']), 
            pokeTuple(name='Oddish', id=43, type=['grass', 'poison']), 
            pokeTuple(name='Gloom', id=44, type=['grass', 'poison']), 
            pokeTuple(name='Vileplume', id=45, type=['grass', 'poison']), 
            pokeTuple(name='Paras', id=46, type=['bug', 'grass']), 
            pokeTuple(name='Parasect', id=47, type=['bug', 'grass']), 
            pokeTuple(name='Venonat', id=48, type=['bug', 'poison']), 
            pokeTuple(name='Venomoth', id=49, type=['bug', 'poison']), 
            pokeTuple(name='Diglett', id=50, type=['ground']), 
            pokeTuple(name='Dugtrio', id=51, type=['ground']), 
            pokeTuple(name='Meowth', id=52, type=['normal']), 
            pokeTuple(name='Persian', id=53, type=['normal']), 
            pokeTuple(name='Psyduck', id=54, type=['water']), 
            pokeTuple(name='Golduck', id=55, type=['water']), 
            pokeTuple(name='Mankey', id=56, type=['fighting']), 
            pokeTuple(name='Primeape', id=57, type=['fighting']), 
            pokeTuple(name='Growlithe', id=58, type=['fire']), 
            pokeTuple(name='Arcanine', id=59, type=['fire']), 
            pokeTuple(name='Poliwag', id=60, type=['water']), 
            pokeTuple(name='Poliwhirl', id=61, type=['water']), 
            pokeTuple(name='Poliwrath', id=62, type=['water', 'fighting']), 
            pokeTuple(name='Abra', id=63, type=['psychic']), 
            pokeTuple(name='Kadabra', id=64, type=['psychic']), 
            pokeTuple(name='Alakazam', id=65, type=['psychic']), 
            pokeTuple(name='Machop', id=66, type=['fighting']), 
            pokeTuple(name='Machoke', id=67, type=['fighting']), 
            pokeTuple(name='Machamp', id=68, type=['fighting']), 
            pokeTuple(name='Bellsprout', id=69, type=['grass', 'poison']), 
            pokeTuple(name='Weepinbell', id=70, type=['grass', 'poison']), 
            pokeTuple(name='Victreebel', id=71, type=['grass', 'poison']), 
            pokeTuple(name='Tentacool', id=72, type=['water', 'poison']), 
            pokeTuple(name='Tentacruel', id=73, type=['water', 'poison']), 
            pokeTuple(name='Geodude', id=74, type=['rock', 'ground']), 
            pokeTuple(name='Graveler', id=75, type=['rock', 'ground']), 
            pokeTuple(name='Golem', id=76, type=['rock', 'ground']), 
            pokeTuple(name='Ponyta', id=77, type=['fire']), 
            pokeTuple(name='Rapidash', id=78, type=['fire']), 
            pokeTuple(name='Slowpoke', id=79, type=['water', 'psychic']), 
            pokeTuple(name='Slowbro', id=80, type=['water', 'psychic']), 
            pokeTuple(name='Magnemite', id=81, type=['electric', 'steel']), 
            pokeTuple(name='Magneton', id=82, type=['electric', 'steel']), 
            pokeTuple(name='Farfetchd', id=83, type=['normal', 'flying']), 
            pokeTuple(name='Doduo', id=84, type=['normal', 'flying']), 
            pokeTuple(name='Dodrio', id=85, type=['normal', 'flying']), 
            pokeTuple(name='Seel', id=86, type=['water']), 
            pokeTuple(name='Dewgong', id=87, type=['water', 'ice']), 
            pokeTuple(name='Grimer', id=88, type=['poison']), 
            pokeTuple(name='Muk', id=89, type=['poison']), 
            pokeTuple(name='Shellder', id=90, type=['water']), 
            pokeTuple(name='Cloyster', id=91, type=['water', 'ice']), 
            pokeTuple(name='Gastly', id=92, type=['ghost', 'poison']), 
            pokeTuple(name='Haunter', id=93, type=['ghost', 'poison']), 
            pokeTuple(name='Gengar', id=94, type=['ghost', 'poison']), 
            pokeTuple(name='Onix', id=95, type=['rock', 'ground']), 
            pokeTuple(name='Drowzee', id=96, type=['psychic']), 
            pokeTuple(name='Hypno', id=97, type=['psychic']), 
            pokeTuple(name='Krabby', id=98, type=['water']), 
            pokeTuple(name='Kingler', id=99, type=['water']), 
            pokeTuple(name='Voltorb', id=100, type=['electric']), 
            pokeTuple(name='Electrode', id=101, type=['electric']), 
            pokeTuple(name='Exeggcute', id=102, type=['grass', 'psychic']), 
            pokeTuple(name='Exeggutor', id=103, type=['grass', 'psychic']), 
            pokeTuple(name='Cubone', id=104, type=['ground']), 
            pokeTuple(name='Marowak', id=105, type=['ground']), 
            pokeTuple(name='Hitmonlee', id=106, type=['fighting']), 
            pokeTuple(name='Hitmonchan', id=107, type=['fighting']), 
            pokeTuple(name='Lickitung', id=108, type=['normal']), 
            pokeTuple(name='Koffing', id=109, type=['poison']), 
            pokeTuple(name='Weezing', id=110, type=['poison']), 
            pokeTuple(name='Rhyhorn', id=111, type=['ground', 'rock']), 
            pokeTuple(name='Rhydon', id=112, type=['ground', 'rock']), 
            pokeTuple(name='Chansey', id=113, type=['normal']), 
            pokeTuple(name='Tangela', id=114, type=['grass']), 
            pokeTuple(name='Kangaskhan', id=115, type=['normal']), 
            pokeTuple(name='Horsea', id=116, type=['water']), 
            pokeTuple(name='Seadra', id=117, type=['water']), 
            pokeTuple(name='Goldeen', id=118, type=['water']), 
            pokeTuple(name='Seaking', id=119, type=['water']), 
            pokeTuple(name='Staryu', id=120, type=['water']), 
            pokeTuple(name='Starmie', id=121, type=['water', 'psychic']), 
            pokeTuple(name='Scyther', id=123, type=['bug', 'flying']), 
            pokeTuple(name='Jynx', id=124, type=['ice', 'psychic']), 
            pokeTuple(name='Electabuzz', id=125, type=['electric']), 
            pokeTuple(name='Magmar', id=126, type=['fire']), 
            pokeTuple(name='Pinsir', id=127, type=['bug']), 
            pokeTuple(name='Tauros', id=128, type=['normal']), 
            pokeTuple(name='Magikarp', id=129, type=['water']), 
            pokeTuple(name='Gyarados', id=130, type=['water', 'flying']), 
            pokeTuple(name='Lapras', id=131, type=['water', 'ice']), 
            pokeTuple(name='Ditto', id=132, type=['normal']), 
            pokeTuple(name='Eevee', id=133, type=['normal']), 
            pokeTuple(name='Vaporeon', id=134, type=['water']), 
            pokeTuple(name='Jolteon', id=135, type=['electric']), 
            pokeTuple(name='Flareon', id=136, type=['fire']), 
            pokeTuple(name='Porygon', id=137, type=['normal']), 
            pokeTuple(name='Omanyte', id=138, type=['rock', 'water']), 
            pokeTuple(name='Omastar', id=139, type=['rock', 'water']), 
            pokeTuple(name='Kabuto', id=140, type=['rock', 'water']), 
            pokeTuple(name='Kabutops', id=141, type=['rock', 'water']), 
            pokeTuple(name='Aerodactyl', id=142, type=['rock', 'flying']), 
            pokeTuple(name='Snorlax', id=143, type=['normal']), 
            pokeTuple(name='Articuno', id=144, type=['ice', 'flying']), 
            pokeTuple(name='Zapdos', id=145, type=['electric', 'flying']), 
            pokeTuple(name='Moltres', id=146, type=['fire', 'flying']), 
            pokeTuple(name='Dratini', id=147, type=['dragon']), 
            pokeTuple(name='Dragonair', id=148, type=['dragon']), 
            pokeTuple(name='Dragonite', id=149, type=['dragon', 'flying']), 
            pokeTuple(name='Mewtwo', id=150, type=['psychic']), 
            pokeTuple(name='Mew', id=151, type=['psychic']), 
            pokeTuple(name='Chikorita', id=152, type=['grass']), 
            pokeTuple(name='Bayleef', id=153, type=['grass']), 
            pokeTuple(name='Meganium', id=154, type=['grass']), 
            pokeTuple(name='Cyndaquil', id=155, type=['fire']), 
            pokeTuple(name='Quilava', id=156, type=['fire']), 
            pokeTuple(name='Typhlosion', id=157, type=['fire']), 
            pokeTuple(name='Totodile', id=158, type=['water']), 
            pokeTuple(name='Croconaw', id=159, type=['water']), 
            pokeTuple(name='Feraligatr', id=160, type=['water']), 
            pokeTuple(name='Sentret', id=161, type=['normal']), 
            pokeTuple(name='Furret', id=162, type=['normal']), 
            pokeTuple(name='Hoothoot', id=163, type=['normal', 'flying']), 
            pokeTuple(name='Noctowl', id=164, type=['normal', 'flying']), 
            pokeTuple(name='Ledyba', id=165, type=['bug', 'flying']), 
            pokeTuple(name='Ledian', id=166, type=['bug', 'flying']), 
            pokeTuple(name='Spinarak', id=167, type=['bug', 'poison']), 
            pokeTuple(name='Ariados', id=168, type=['bug', 'poison']), 
            pokeTuple(name='Crobat', id=169, type=['poison', 'flying']), 
            pokeTuple(name='Chinchou', id=170, type=['water', 'electric']), 
            pokeTuple(name='Lanturn', id=171, type=['water', 'electric']), 
            pokeTuple(name='Pichu', id=172, type=['electric']), 
            pokeTuple(name='Cleffa', id=173, type=['fairy']), 
            pokeTuple(name='Igglybuff', id=174, type=['normal', 'fairy']), 
            pokeTuple(name='Togepi', id=175, type=['fairy']), 
            pokeTuple(name='Togetic', id=176, type=['fairy', 'flying']), 
            pokeTuple(name='Natu', id=177, type=['psychic', 'flying']), 
            pokeTuple(name='Xatu', id=178, type=['psychic', 'flying']), 
            pokeTuple(name='Mareep', id=179, type=['electric']), 
            pokeTuple(name='Flaaffy', id=180, type=['electric']), 
            pokeTuple(name='Ampharos', id=181, type=['electric']), 
            pokeTuple(name='Bellossom', id=182, type=['grass']), 
            pokeTuple(name='Marill', id=183, type=['water', 'fairy']), 
            pokeTuple(name='Azumarill', id=184, type=['water', 'fairy']), 
            pokeTuple(name='Sudowoodo', id=185, type=['rock']), 
            pokeTuple(name='Politoed', id=186, type=['water']), 
            pokeTuple(name='Hoppip', id=187, type=['grass', 'flying']), 
            pokeTuple(name='Skiploom', id=188, type=['grass', 'flying']), 
            pokeTuple(name='Jumpluff', id=189, type=['grass', 'flying']), 
            pokeTuple(name='Aipom', id=190, type=['normal']), 
            pokeTuple(name='Sunkern', id=191, type=['grass']), 
            pokeTuple(name='Sunflora', id=192, type=['grass']), 
            pokeTuple(name='Yanma', id=193, type=['bug', 'flying']), 
            pokeTuple(name='Wooper', id=194, type=['water', 'ground']), 
            pokeTuple(name='Quagsire', id=195, type=['water', 'ground']), 
            pokeTuple(name='Espeon', id=196, type=['psychic']), 
            pokeTuple(name='Umbreon', id=197, type=['dark']), 
            pokeTuple(name='Murkrow', id=198, type=['dark', 'flying']), 
            pokeTuple(name='Slowking', id=199, type=['water', 'psychic']), 
            pokeTuple(name='Misdreavus', id=200, type=['ghost']), 
            pokeTuple(name='Unown', id=201, type=['psychic']), 
            pokeTuple(name='Wobbuffet', id=202, type=['psychic']), 
            pokeTuple(name='Girafarig', id=203, type=['normal', 'psychic']), 
            pokeTuple(name='Pineco', id=204, type=['bug']), 
            pokeTuple(name='Forretress', id=205, type=['bug', 'steel']), 
            pokeTuple(name='Dunsparce', id=206, type=['normal']), 
            pokeTuple(name='Gligar', id=207, type=['ground', 'flying']), 
            pokeTuple(name='Steelix', id=208, type=['steel', 'ground']), 
            pokeTuple(name='Snubbull', id=209, type=['fairy']), 
            pokeTuple(name='Granbull', id=210, type=['fairy']), 
            pokeTuple(name='Qwilfish', id=211, type=['water', 'poison']), 
            pokeTuple(name='Scizor', id=212, type=['bug', 'steel']), 
            pokeTuple(name='Shuckle', id=213, type=['bug', 'rock']), 
            pokeTuple(name='Heracross', id=214, type=['bug', 'fighting']), 
            pokeTuple(name='Sneasel', id=215, type=['dark', 'ice']), 
            pokeTuple(name='Teddiursa', id=216, type=['normal']), 
            pokeTuple(name='Ursaring', id=217, type=['normal']), 
            pokeTuple(name='Slugma', id=218, type=['fire']), 
            pokeTuple(name='Magcargo', id=219, type=['fire', 'rock']), 
            pokeTuple(name='Swinub', id=220, type=['ice', 'ground']), 
            pokeTuple(name='Piloswine', id=221, type=['ice', 'ground']), 
            pokeTuple(name='Corsola', id=222, type=['water', 'rock']), 
            pokeTuple(name='Remoraid', id=223, type=['water']), 
            pokeTuple(name='Octillery', id=224, type=['water']), 
            pokeTuple(name='Delibird', id=225, type=['ice', 'flying']), 
            pokeTuple(name='Mantine', id=226, type=['water', 'flying']), 
            pokeTuple(name='Skarmory', id=227, type=['steel', 'flying']), 
            pokeTuple(name='Houndour', id=228, type=['dark', 'fire']), 
            pokeTuple(name='Houndoom', id=229, type=['dark', 'fire']), 
            pokeTuple(name='Kingdra', id=230, type=['water', 'dragon']), 
            pokeTuple(name='Phanpy', id=231, type=['ground']), 
            pokeTuple(name='Donphan', id=232, type=['ground']), 
            pokeTuple(name='Porygon2', id=233, type=['normal']), 
            pokeTuple(name='Stantler', id=234, type=['normal']), 
            pokeTuple(name='Smeargle', id=235, type=['normal']), 
            pokeTuple(name='Tyrogue', id=236, type=['fighting']), 
            pokeTuple(name='Hitmontop', id=237, type=['fighting']), 
            pokeTuple(name='Smoochum', id=238, type=['ice', 'psychic']), 
            pokeTuple(name='Elekid', id=239, type=['electric']), 
            pokeTuple(name='Magby', id=240, type=['fire']), 
            pokeTuple(name='Miltank', id=241, type=['normal']), 
            pokeTuple(name='Blissey', id=242, type=['normal']), 
            pokeTuple(name='Raikou', id=243, type=['electric']), 
            pokeTuple(name='Entei', id=244, type=['fire']), 
            pokeTuple(name='Suicune', id=245, type=['water']), 
            pokeTuple(name='Larvitar', id=246, type=['rock', 'ground']), 
            pokeTuple(name='Pupitar', id=247, type=['rock', 'ground']), 
            pokeTuple(name='Tyranitar', id=248, type=['rock', 'dark']), 
            pokeTuple(name='Lugia', id=249, type=['psychic', 'flying']), 
            pokeTuple(name='Celebi', id=251, type=['psychic', 'grass']), 
            pokeTuple(name='Treecko', id=252, type=['grass']), 
            pokeTuple(name='Grovyle', id=253, type=['grass']), 
            pokeTuple(name='Sceptile', id=254, type=['grass']), 
            pokeTuple(name='Torchic', id=255, type=['fire']), 
            pokeTuple(name='Combusken', id=256, type=['fire', 'fighting']), 
            pokeTuple(name='Blaziken', id=257, type=['fire', 'fighting']), 
            pokeTuple(name='Mudkip', id=258, type=['water']), 
            pokeTuple(name='Marshtomp', id=259, type=['water', 'ground']), 
            pokeTuple(name='Swampert', id=260, type=['water', 'ground']), 
            pokeTuple(name='Poochyena', id=261, type=['dark']), 
            pokeTuple(name='Mightyena', id=262, type=['dark']), 
            pokeTuple(name='Zigzagoon', id=263, type=['normal']), 
            pokeTuple(name='Linoone', id=264, type=['normal']), 
            pokeTuple(name='Wurmple', id=265, type=['bug']), 
            pokeTuple(name='Silcoon', id=266, type=['bug']), 
            pokeTuple(name='Beautifly', id=267, type=['bug', 'flying']), 
            pokeTuple(name='Cascoon', id=268, type=['bug']), 
            pokeTuple(name='Dustox', id=269, type=['bug', 'poison']), 
            pokeTuple(name='Lotad', id=270, type=['water', 'grass']), 
            pokeTuple(name='Lombre', id=271, type=['water', 'grass']), 
            pokeTuple(name='Ludicolo', id=272, type=['water', 'grass']), 
            pokeTuple(name='Seedot', id=273, type=['grass']), 
            pokeTuple(name='Nuzleaf', id=274, type=['grass', 'dark']), 
            pokeTuple(name='Shiftry', id=275, type=['grass', 'dark']), 
            pokeTuple(name='Taillow', id=276, type=['normal', 'flying']), 
            pokeTuple(name='Swellow', id=277, type=['normal', 'flying']), 
            pokeTuple(name='Wingull', id=278, type=['water', 'flying']), 
            pokeTuple(name='Pelipper', id=279, type=['water', 'flying']), 
            pokeTuple(name='Ralts', id=280, type=['psychic', 'fairy']), 
            pokeTuple(name='Kirlia', id=281, type=['psychic', 'fairy']), 
            pokeTuple(name='Gardevoir', id=282, type=['psychic', 'fairy']), 
            pokeTuple(name='Surskit', id=283, type=['bug', 'water']), 
            pokeTuple(name='Masquerain', id=284, type=['bug', 'flying']), 
            pokeTuple(name='Shroomish', id=285, type=['grass']), 
            pokeTuple(name='Breloom', id=286, type=['grass', 'fighting']), 
            pokeTuple(name='Slakoth', id=287, type=['normal']), 
            pokeTuple(name='Vigoroth', id=288, type=['normal']), 
            pokeTuple(name='Slaking', id=289, type=['normal']), 
            pokeTuple(name='Nincada', id=290, type=['bug', 'ground']), 
            pokeTuple(name='Ninjask', id=291, type=['bug', 'flying']), 
            pokeTuple(name='Shedinja', id=292, type=['bug', 'ghost']), 
            pokeTuple(name='Whismur', id=293, type=['normal']), 
            pokeTuple(name='Loudred', id=294, type=['normal']), 
            pokeTuple(name='Exploud', id=295, type=['normal']), 
            pokeTuple(name='Makuhita', id=296, type=['fighting']), 
            pokeTuple(name='Hariyama', id=297, type=['fighting']), 
            pokeTuple(name='Azurill', id=298, type=['normal', 'fairy']), 
            pokeTuple(name='Nosepass', id=299, type=['rock']), 
            pokeTuple(name='Skitty', id=300, type=['normal']), 
            pokeTuple(name='Delcatty', id=301, type=['normal']), 
            pokeTuple(name='Sableye', id=302, type=['dark', 'ghost']), 
            pokeTuple(name='Mawile', id=303, type=['steel', 'fairy']), 
            pokeTuple(name='Aron', id=304, type=['steel', 'rock']), 
            pokeTuple(name='Lairon', id=305, type=['steel', 'rock']), 
            pokeTuple(name='Aggron', id=306, type=['steel', 'rock']), 
            pokeTuple(name='Meditite', id=307, type=['fighting', 'psychic']), 
            pokeTuple(name='Medicham', id=308, type=['fighting', 'psychic']), 
            pokeTuple(name='Electrike', id=309, type=['electric']), 
            pokeTuple(name='Manectric', id=310, type=['electric']), 
            pokeTuple(name='Plusle', id=311, type=['electric']), 
            pokeTuple(name='Minun', id=312, type=['electric']), 
            pokeTuple(name='Volbeat', id=313, type=['bug']), 
            pokeTuple(name='Illumise', id=314, type=['bug']), 
            pokeTuple(name='Roselia', id=315, type=['grass', 'poison']), 
            pokeTuple(name='Gulpin', id=316, type=['poison']), 
            pokeTuple(name='Swalot', id=317, type=['poison']), 
            pokeTuple(name='Carvanha', id=318, type=['water', 'dark']), 
            pokeTuple(name='Sharpedo', id=319, type=['water', 'dark']), 
            pokeTuple(name='Wailmer', id=320, type=['water']), 
            pokeTuple(name='Wailord', id=321, type=['water']), 
            pokeTuple(name='Numel', id=322, type=['fire', 'ground']), 
            pokeTuple(name='Camerupt', id=323, type=['fire', 'ground']), 
            pokeTuple(name='Torkoal', id=324, type=['fire']), 
            pokeTuple(name='Spoink', id=325, type=['psychic']), 
            pokeTuple(name='Grumpig', id=326, type=['psychic']), 
            pokeTuple(name='Spinda', id=327, type=['normal']), 
            pokeTuple(name='Trapinch', id=328, type=['ground']), 
            pokeTuple(name='Vibrava', id=329, type=['ground', 'dragon']), 
            pokeTuple(name='Flygon', id=330, type=['ground', 'dragon']), 
            pokeTuple(name='Cacnea', id=331, type=['grass']), 
            pokeTuple(name='Cacturne', id=332, type=['grass', 'dark']), 
            pokeTuple(name='Swablu', id=333, type=['normal', 'flying']), 
            pokeTuple(name='Altaria', id=334, type=['dragon', 'flying']), 
            pokeTuple(name='Zangoose', id=335, type=['normal']), 
            pokeTuple(name='Seviper', id=336, type=['poison']), 
            pokeTuple(name='Lunatone', id=337, type=['rock', 'psychic']), 
            pokeTuple(name='Solrock', id=338, type=['rock', 'psychic']), 
            pokeTuple(name='Barboach', id=339, type=['water', 'ground']), 
            pokeTuple(name='Whiscash', id=340, type=['water', 'ground']), 
            pokeTuple(name='Corphish', id=341, type=['water']), 
            pokeTuple(name='Crawdaunt', id=342, type=['water', 'dark']), 
            pokeTuple(name='Baltoy', id=343, type=['ground', 'psychic']), 
            pokeTuple(name='Claydol', id=344, type=['ground', 'psychic']), 
            pokeTuple(name='Lileep', id=345, type=['rock', 'grass']), 
            pokeTuple(name='Cradily', id=346, type=['rock', 'grass']), 
            pokeTuple(name='Anorith', id=347, type=['rock', 'bug']), 
            pokeTuple(name='Armaldo', id=348, type=['rock', 'bug']), 
            pokeTuple(name='Feebas', id=349, type=['water']), 
            pokeTuple(name='Milotic', id=350, type=['water']), 
            pokeTuple(name='Castform', id=351, type=['normal']), 
            pokeTuple(name='Kecleon', id=352, type=['normal']), 
            pokeTuple(name='Shuppet', id=353, type=['ghost']), 
            pokeTuple(name='Banette', id=354, type=['ghost']), 
            pokeTuple(name='Duskull', id=355, type=['ghost']), 
            pokeTuple(name='Dusclops', id=356, type=['ghost']), 
            pokeTuple(name='Tropius', id=357, type=['grass', 'flying']), 
            pokeTuple(name='Chimecho', id=358, type=['psychic']), 
            pokeTuple(name='Absol', id=359, type=['dark']), 
            pokeTuple(name='Wynaut', id=360, type=['psychic']), 
            pokeTuple(name='Snorunt', id=361, type=['ice']), 
            pokeTuple(name='Glalie', id=362, type=['ice']), 
            pokeTuple(name='Spheal', id=363, type=['ice', 'water']), 
            pokeTuple(name='Sealeo', id=364, type=['ice', 'water']), 
            pokeTuple(name='Walrein', id=365, type=['ice', 'water']), 
            pokeTuple(name='Clamperl', id=366, type=['water']), 
            pokeTuple(name='Huntail', id=367, type=['water']), 
            pokeTuple(name='Gorebyss', id=368, type=['water']), 
            pokeTuple(name='Relicanth', id=369, type=['water', 'rock']), 
            pokeTuple(name='Luvdisc', id=370, type=['water']), 
            pokeTuple(name='Bagon', id=371, type=['dragon']), 
            pokeTuple(name='Shelgon', id=372, type=['dragon']), 
            pokeTuple(name='Salamence', id=373, type=['dragon', 'flying']), 
            pokeTuple(name='Beldum', id=374, type=['steel', 'psychic']), 
            pokeTuple(name='Metang', id=375, type=['steel', 'psychic']), 
            pokeTuple(name='Metagross', id=376, type=['steel', 'psychic']), 
            pokeTuple(name='Regirock', id=377, type=['rock']), 
            pokeTuple(name='Regice', id=378, type=['ice']), 
            pokeTuple(name='Registeel', id=379, type=['steel']), 
            pokeTuple(name='Latias', id=380, type=['dragon', 'psychic']), 
            pokeTuple(name='Latios', id=381, type=['dragon', 'psychic']), 
            pokeTuple(name='Kyogre', id=382, type=['water']), 
            pokeTuple(name='Groudon', id=383, type=['ground']), 
            pokeTuple(name='Rayquaza', id=384, type=['dragon', 'flying']), 
            pokeTuple(name='Jirachi', id=385, type=['steel', 'psychic']), 
            pokeTuple(name='Turtwig', id=387, type=['grass']), 
            pokeTuple(name='Grotle', id=388, type=['grass']), 
            pokeTuple(name='Torterra', id=389, type=['grass', 'ground']), 
            pokeTuple(name='Chimchar', id=390, type=['fire']), 
            pokeTuple(name='Monferno', id=391, type=['fire', 'fighting']), 
            pokeTuple(name='Infernape', id=392, type=['fire', 'fighting']), 
            pokeTuple(name='Piplup', id=393, type=['water']), 
            pokeTuple(name='Prinplup', id=394, type=['water']), 
            pokeTuple(name='Empoleon', id=395, type=['water', 'steel']), 
            pokeTuple(name='Starly', id=396, type=['normal', 'flying']), 
            pokeTuple(name='Staravia', id=397, type=['normal', 'flying']), 
            pokeTuple(name='Staraptor', id=398, type=['normal', 'flying']), 
            pokeTuple(name='Bidoof', id=399, type=['normal']), 
            pokeTuple(name='Bibarel', id=400, type=['normal', 'water']), 
            pokeTuple(name='Kricketot', id=401, type=['bug']), 
            pokeTuple(name='Kricketune', id=402, type=['bug']), 
            pokeTuple(name='Shinx', id=403, type=['electric']), 
            pokeTuple(name='Luxio', id=404, type=['electric']), 
            pokeTuple(name='Luxray', id=405, type=['electric']), 
            pokeTuple(name='Budew', id=406, type=['grass', 'poison']), 
            pokeTuple(name='Roserade', id=407, type=['grass', 'poison']), 
            pokeTuple(name='Cranidos', id=408, type=['rock']), 
            pokeTuple(name='Rampardos', id=409, type=['rock']), 
            pokeTuple(name='Shieldon', id=410, type=['rock', 'steel']), 
            pokeTuple(name='Bastiodon', id=411, type=['rock', 'steel']), 
            pokeTuple(name='Burmy', id=412, type=['bug']), 
            pokeTuple(name='Mothim', id=414, type=['bug', 'flying']), 
            pokeTuple(name='Combee', id=415, type=['bug', 'flying']), 
            pokeTuple(name='Vespiquen', id=416, type=['bug', 'flying']), 
            pokeTuple(name='Pachirisu', id=417, type=['electric']), 
            pokeTuple(name='Buizel', id=418, type=['water']), 
            pokeTuple(name='Floatzel', id=419, type=['water']), 
            pokeTuple(name='Cherubi', id=420, type=['grass']), 
            pokeTuple(name='Cherrim', id=421, type=['grass']), 
            pokeTuple(name='Shellos', id=422, type=['water']), 
            pokeTuple(name='Gastrodon', id=423, type=['water', 'ground']), 
            pokeTuple(name='Ambipom', id=424, type=['normal']), 
            pokeTuple(name='Drifloon', id=425, type=['ghost', 'flying']), 
            pokeTuple(name='Drifblim', id=426, type=['ghost', 'flying']), 
            pokeTuple(name='Buneary', id=427, type=['normal']), 
            pokeTuple(name='Lopunny', id=428, type=['normal']), 
            pokeTuple(name='Mismagius', id=429, type=['ghost']), 
            pokeTuple(name='Honchkrow', id=430, type=['dark', 'flying']), 
            pokeTuple(name='Glameow', id=431, type=['normal']), 
            pokeTuple(name='Purugly', id=432, type=['normal']), 
            pokeTuple(name='Chingling', id=433, type=['psychic']), 
            pokeTuple(name='Stunky', id=434, type=['poison', 'dark']), 
            pokeTuple(name='Skuntank', id=435, type=['poison', 'dark']), 
            pokeTuple(name='Bronzor', id=436, type=['steel', 'psychic']), 
            pokeTuple(name='Bronzong', id=437, type=['steel', 'psychic']), 
            pokeTuple(name='Bonsly', id=438, type=['rock']), 
            pokeTuple(name='Happiny', id=440, type=['normal']), 
            pokeTuple(name='Chatot', id=441, type=['normal', 'flying']), 
            pokeTuple(name='Spiritomb', id=442, type=['ghost', 'dark']), 
            pokeTuple(name='Gible', id=443, type=['dragon', 'ground']), 
            pokeTuple(name='Gabite', id=444, type=['dragon', 'ground']), 
            pokeTuple(name='Garchomp', id=445, type=['dragon', 'ground']), 
            pokeTuple(name='Munchlax', id=446, type=['normal']), 
            pokeTuple(name='Riolu', id=447, type=['fighting']), 
            pokeTuple(name='Lucario', id=448, type=['fighting', 'steel']), 
            pokeTuple(name='Hippopotas', id=449, type=['ground']), 
            pokeTuple(name='Hippowdon', id=450, type=['ground']), 
            pokeTuple(name='Skorupi', id=451, type=['poison', 'bug']), 
            pokeTuple(name='Drapion', id=452, type=['poison', 'dark']), 
            pokeTuple(name='Croagunk', id=453, type=['poison', 'fighting']), 
            pokeTuple(name='Toxicroak', id=454, type=['poison', 'fighting']), 
            pokeTuple(name='Carnivine', id=455, type=['grass']), 
            pokeTuple(name='Finneon', id=456, type=['water']), 
            pokeTuple(name='Lumineon', id=457, type=['water']), 
            pokeTuple(name='Mantyke', id=458, type=['water', 'flying']), 
            pokeTuple(name='Snover', id=459, type=['grass', 'ice']), 
            pokeTuple(name='Abomasnow', id=460, type=['grass', 'ice']), 
            pokeTuple(name='Weavile', id=461, type=['dark', 'ice']), 
            pokeTuple(name='Magnezone', id=462, type=['electric', 'steel']), 
            pokeTuple(name='Lickilicky', id=463, type=['normal']), 
            pokeTuple(name='Rhyperior', id=464, type=['ground', 'rock']), 
            pokeTuple(name='Tangrowth', id=465, type=['grass']), 
            pokeTuple(name='Electivire', id=466, type=['electric']), 
            pokeTuple(name='Magmortar', id=467, type=['fire']), 
            pokeTuple(name='Togekiss', id=468, type=['fairy', 'flying']), 
            pokeTuple(name='Yanmega', id=469, type=['bug', 'flying']), 
            pokeTuple(name='Leafeon', id=470, type=['grass']), 
            pokeTuple(name='Glaceon', id=471, type=['ice']), 
            pokeTuple(name='Gliscor', id=472, type=['ground', 'flying']), 
            pokeTuple(name='Mamoswine', id=473, type=['ice', 'ground']), 
            pokeTuple(name='Gallade', id=475, type=['psychic', 'fighting']), 
            pokeTuple(name='Probopass', id=476, type=['rock', 'steel']), 
            pokeTuple(name='Dusknoir', id=477, type=['ghost']), 
            pokeTuple(name='Froslass', id=478, type=['ice', 'ghost']), 
            pokeTuple(name='Rotom', id=479, type=['electric', 'ghost']), 
            pokeTuple(name='Uxie', id=480, type=['psychic']), 
            pokeTuple(name='Mesprit', id=481, type=['psychic']), 
            pokeTuple(name='Azelf', id=482, type=['psychic']), 
            pokeTuple(name='Dialga', id=483, type=['steel', 'dragon']), 
            pokeTuple(name='Palkia', id=484, type=['water', 'dragon']), 
            pokeTuple(name='Heatran', id=485, type=['fire', 'steel']), 
            pokeTuple(name='Regigigas', id=486, type=['normal']), 
            pokeTuple(name='Cresselia', id=488, type=['psychic']), 
            pokeTuple(name='Phione', id=489, type=['water']), 
            pokeTuple(name='Manaphy', id=490, type=['water']), 
            pokeTuple(name='Darkrai', id=491, type=['dark']), 
            pokeTuple(name='Arceus', id=493, type=['normal']), 
            pokeTuple(name='Victini', id=494, type=['psychic', 'fire']), 
            pokeTuple(name='Snivy', id=495, type=['grass']), 
            pokeTuple(name='Servine', id=496, type=['grass']), 
            pokeTuple(name='Serperior', id=497, type=['grass']), 
            pokeTuple(name='Tepig', id=498, type=['fire']), 
            pokeTuple(name='Pignite', id=499, type=['fire', 'fighting']), 
            pokeTuple(name='Emboar', id=500, type=['fire', 'fighting']), 
            pokeTuple(name='Oshawott', id=501, type=['water']), 
            pokeTuple(name='Dewott', id=502, type=['water']), 
            pokeTuple(name='Samurott', id=503, type=['water']), 
            pokeTuple(name='Patrat', id=504, type=['normal']), 
            pokeTuple(name='Watchog', id=505, type=['normal']), 
            pokeTuple(name='Lillipup', id=506, type=['normal']), 
            pokeTuple(name='Herdier', id=507, type=['normal']), 
            pokeTuple(name='Stoutland', id=508, type=['normal']), 
            pokeTuple(name='Purrloin', id=509, type=['dark']), 
            pokeTuple(name='Liepard', id=510, type=['dark']), 
            pokeTuple(name='Pansage', id=511, type=['grass']), 
            pokeTuple(name='Simisage', id=512, type=['grass']), 
            pokeTuple(name='Pansear', id=513, type=['fire']), 
            pokeTuple(name='Simisear', id=514, type=['fire']), 
            pokeTuple(name='Panpour', id=515, type=['water']), 
            pokeTuple(name='Simipour', id=516, type=['water']), 
            pokeTuple(name='Munna', id=517, type=['psychic']), 
            pokeTuple(name='Musharna', id=518, type=['psychic']), 
            pokeTuple(name='Pidove', id=519, type=['normal', 'flying']), 
            pokeTuple(name='Tranquill', id=520, type=['normal', 'flying']), 
            pokeTuple(name='Unfezant', id=521, type=['normal', 'flying']), 
            pokeTuple(name='Blitzle', id=522, type=['electric']), 
            pokeTuple(name='Zebstrika', id=523, type=['electric']), 
            pokeTuple(name='Roggenrola', id=524, type=['rock']), 
            pokeTuple(name='Boldore', id=525, type=['rock']), 
            pokeTuple(name='Gigalith', id=526, type=['rock']), 
            pokeTuple(name='Woobat', id=527, type=['psychic', 'flying']), 
            pokeTuple(name='Swoobat', id=528, type=['psychic', 'flying']), 
            pokeTuple(name='Drilbur', id=529, type=['ground']), 
            pokeTuple(name='Excadrill', id=530, type=['ground', 'steel']), 
            pokeTuple(name='Audino', id=531, type=['normal']), 
            pokeTuple(name='Timburr', id=532, type=['fighting']), 
            pokeTuple(name='Gurdurr', id=533, type=['fighting']), 
            pokeTuple(name='Conkeldurr', id=534, type=['fighting']), 
            pokeTuple(name='Tympole', id=535, type=['water']), 
            pokeTuple(name='Palpitoad', id=536, type=['water', 'ground']), 
            pokeTuple(name='Seismitoad', id=537, type=['water', 'ground']), 
            pokeTuple(name='Throh', id=538, type=['fighting']), 
            pokeTuple(name='Sawk', id=539, type=['fighting']), 
            pokeTuple(name='Sewaddle', id=540, type=['bug', 'grass']), 
            pokeTuple(name='Swadloon', id=541, type=['bug', 'grass']), 
            pokeTuple(name='Leavanny', id=542, type=['bug', 'grass']), 
            pokeTuple(name='Venipede', id=543, type=['bug', 'poison']), 
            pokeTuple(name='Whirlipede', id=544, type=['bug', 'poison']), 
            pokeTuple(name='Scolipede', id=545, type=['bug', 'poison']), 
            pokeTuple(name='Cottonee', id=546, type=['grass', 'fairy']), 
            pokeTuple(name='Whimsicott', id=547, type=['grass', 'fairy']), 
            pokeTuple(name='Petilil', id=548, type=['grass']), 
            pokeTuple(name='Lilligant', id=549, type=['grass']), 
            pokeTuple(name='Sandile', id=551, type=['ground', 'dark']), 
            pokeTuple(name='Krokorok', id=552, type=['ground', 'dark']), 
            pokeTuple(name='Krookodile', id=553, type=['ground', 'dark']), 
            pokeTuple(name='Darumaka', id=554, type=['fire']), 
            pokeTuple(name='Maractus', id=556, type=['grass']), 
            pokeTuple(name='Dwebble', id=557, type=['bug', 'rock']), 
            pokeTuple(name='Crustle', id=558, type=['bug', 'rock']), 
            pokeTuple(name='Scraggy', id=559, type=['dark', 'fighting']), 
            pokeTuple(name='Scrafty', id=560, type=['dark', 'fighting']), 
            pokeTuple(name='Sigilyph', id=561, type=['psychic', 'flying']), 
            pokeTuple(name='Yamask', id=562, type=['ghost']), 
            pokeTuple(name='Cofagrigus', id=563, type=['ghost']), 
            pokeTuple(name='Tirtouga', id=564, type=['water', 'rock']), 
            pokeTuple(name='Carracosta', id=565, type=['water', 'rock']), 
            pokeTuple(name='Archen', id=566, type=['rock', 'flying']), 
            pokeTuple(name='Archeops', id=567, type=['rock', 'flying']), 
            pokeTuple(name='Trubbish', id=568, type=['poison']), 
            pokeTuple(name='Garbodor', id=569, type=['poison']), 
            pokeTuple(name='Zorua', id=570, type=['dark']), 
            pokeTuple(name='Zoroark', id=571, type=['dark']), 
            pokeTuple(name='Minccino', id=572, type=['normal']), 
            pokeTuple(name='Cinccino', id=573, type=['normal']), 
            pokeTuple(name='Gothita', id=574, type=['psychic']), 
            pokeTuple(name='Gothorita', id=575, type=['psychic']), 
            pokeTuple(name='Gothitelle', id=576, type=['psychic']), 
            pokeTuple(name='Solosis', id=577, type=['psychic']), 
            pokeTuple(name='Duosion', id=578, type=['psychic']), 
            pokeTuple(name='Reuniclus', id=579, type=['psychic']), 
            pokeTuple(name='Ducklett', id=580, type=['water', 'flying']), 
            pokeTuple(name='Swanna', id=581, type=['water', 'flying']), 
            pokeTuple(name='Vanillite', id=582, type=['ice']), 
            pokeTuple(name='Vanillish', id=583, type=['ice']), 
            pokeTuple(name='Vanilluxe', id=584, type=['ice']), 
            pokeTuple(name='Deerling', id=585, type=['normal', 'grass']), 
            pokeTuple(name='Sawsbuck', id=586, type=['normal', 'grass']), 
            pokeTuple(name='Emolga', id=587, type=['electric', 'flying']), 
            pokeTuple(name='Karrablast', id=588, type=['bug']), 
            pokeTuple(name='Escavalier', id=589, type=['bug', 'steel']), 
            pokeTuple(name='Foongus', id=590, type=['grass', 'poison']), 
            pokeTuple(name='Amoonguss', id=591, type=['grass', 'poison']), 
            pokeTuple(name='Frillish', id=592, type=['water', 'ghost']), 
            pokeTuple(name='Jellicent', id=593, type=['water', 'ghost']), 
            pokeTuple(name='Alomomola', id=594, type=['water']), 
            pokeTuple(name='Joltik', id=595, type=['bug', 'electric']), 
            pokeTuple(name='Galvantula', id=596, type=['bug', 'electric']), 
            pokeTuple(name='Ferroseed', id=597, type=['grass', 'steel']), 
            pokeTuple(name='Ferrothorn', id=598, type=['grass', 'steel']), 
            pokeTuple(name='Klink', id=599, type=['steel']), 
            pokeTuple(name='Klang', id=600, type=['steel']), 
            pokeTuple(name='Klinklang', id=601, type=['steel']), 
            pokeTuple(name='Tynamo', id=602, type=['electric']), 
            pokeTuple(name='Eelektrik', id=603, type=['electric']), 
            pokeTuple(name='Eelektross', id=604, type=['electric']), 
            pokeTuple(name='Elgyem', id=605, type=['psychic']), 
            pokeTuple(name='Beheeyem', id=606, type=['psychic']), 
            pokeTuple(name='Litwick', id=607, type=['ghost', 'fire']), 
            pokeTuple(name='Lampent', id=608, type=['ghost', 'fire']), 
            pokeTuple(name='Chandelure', id=609, type=['ghost', 'fire']), 
            pokeTuple(name='Axew', id=610, type=['dragon']), 
            pokeTuple(name='Fraxure', id=611, type=['dragon']), 
            pokeTuple(name='Haxorus', id=612, type=['dragon']), 
            pokeTuple(name='Cubchoo', id=613, type=['ice']), 
            pokeTuple(name='Beartic', id=614, type=['ice']), 
            pokeTuple(name='Cryogonal', id=615, type=['ice']), 
            pokeTuple(name='Shelmet', id=616, type=['bug']), 
            pokeTuple(name='Accelgor', id=617, type=['bug']), 
            pokeTuple(name='Stunfisk', id=618, type=['ground', 'electric']), 
            pokeTuple(name='Mienfoo', id=619, type=['fighting']), 
            pokeTuple(name='Mienshao', id=620, type=['fighting']), 
            pokeTuple(name='Druddigon', id=621, type=['dragon']), 
            pokeTuple(name='Golett', id=622, type=['ground', 'ghost']), 
            pokeTuple(name='Golurk', id=623, type=['ground', 'ghost']), 
            pokeTuple(name='Pawniard', id=624, type=['dark', 'steel']), 
            pokeTuple(name='Bisharp', id=625, type=['dark', 'steel']), 
            pokeTuple(name='Bouffalant', id=626, type=['normal']), 
            pokeTuple(name='Rufflet', id=627, type=['normal', 'flying']), 
            pokeTuple(name='Braviary', id=628, type=['normal', 'flying']), 
            pokeTuple(name='Vullaby', id=629, type=['dark', 'flying']), 
            pokeTuple(name='Mandibuzz', id=630, type=['dark', 'flying']), 
            pokeTuple(name='Heatmor', id=631, type=['fire']), 
            pokeTuple(name='Durant', id=632, type=['bug', 'steel']), 
            pokeTuple(name='Deino', id=633, type=['dark', 'dragon']), 
            pokeTuple(name='Zweilous', id=634, type=['dark', 'dragon']), 
            pokeTuple(name='Hydreigon', id=635, type=['dark', 'dragon']), 
            pokeTuple(name='Larvesta', id=636, type=['bug', 'fire']), 
            pokeTuple(name='Volcarona', id=637, type=['bug', 'fire']), 
            pokeTuple(name='Cobalion', id=638, type=['steel', 'fighting']), 
            pokeTuple(name='Terrakion', id=639, type=['rock', 'fighting']), 
            pokeTuple(name='Virizion', id=640, type=['grass', 'fighting']), 
            pokeTuple(name='Reshiram', id=643, type=['dragon', 'fire']), 
            pokeTuple(name='Zekrom', id=644, type=['dragon', 'electric']), 
            pokeTuple(name='Kyurem', id=646, type=['dragon', 'ice']), 
            pokeTuple(name='Genesect', id=649, type=['bug', 'steel']), 
            pokeTuple(name='Chespin', id=650, type=['grass']), 
            pokeTuple(name='Quilladin', id=651, type=['grass']), 
            pokeTuple(name='Chesnaught', id=652, type=['grass', 'fighting']), 
            pokeTuple(name='Fennekin', id=653, type=['fire']), 
            pokeTuple(name='Braixen', id=654, type=['fire']), 
            pokeTuple(name='Delphox', id=655, type=['fire', 'psychic']), 
            pokeTuple(name='Froakie', id=656, type=['water']), 
            pokeTuple(name='Frogadier', id=657, type=['water']), 
            pokeTuple(name='Greninja', id=658, type=['water', 'dark']), 
            pokeTuple(name='Bunnelby', id=659, type=['normal']), 
            pokeTuple(name='Diggersby', id=660, type=['normal', 'ground']), 
            pokeTuple(name='Fletchling', id=661, type=['normal', 'flying']), 
            pokeTuple(name='Fletchinder', id=662, type=['fire', 'flying']), 
            pokeTuple(name='Talonflame', id=663, type=['fire', 'flying']), 
            pokeTuple(name='Scatterbug', id=664, type=['bug']), 
            pokeTuple(name='Spewpa', id=665, type=['bug']), 
            pokeTuple(name='Vivillon', id=666, type=['bug', 'flying']), 
            pokeTuple(name='Litleo', id=667, type=['fire', 'normal']), 
            pokeTuple(name='Pyroar', id=668, type=['fire', 'normal']), 
            pokeTuple(name='Flabebe', id=669, type=['fairy']), 
            pokeTuple(name='Floette', id=670, type=['fairy']), 
            pokeTuple(name='Florges', id=671, type=['fairy']), 
            pokeTuple(name='Skiddo', id=672, type=['grass']), 
            pokeTuple(name='Gogoat', id=673, type=['grass']), 
            pokeTuple(name='Pancham', id=674, type=['fighting']), 
            pokeTuple(name='Pangoro', id=675, type=['fighting', 'dark']), 
            pokeTuple(name='Furfrou', id=676, type=['normal']), 
            pokeTuple(name='Espurr', id=677, type=['psychic']), 
            pokeTuple(name='Honedge', id=679, type=['steel', 'ghost']), 
            pokeTuple(name='Doublade', id=680, type=['steel', 'ghost']), 
            pokeTuple(name='Spritzee', id=682, type=['fairy']), 
            pokeTuple(name='Aromatisse', id=683, type=['fairy']), 
            pokeTuple(name='Swirlix', id=684, type=['fairy']), 
            pokeTuple(name='Slurpuff', id=685, type=['fairy']), 
            pokeTuple(name='Inkay', id=686, type=['dark', 'psychic']), 
            pokeTuple(name='Malamar', id=687, type=['dark', 'psychic']), 
            pokeTuple(name='Binacle', id=688, type=['rock', 'water']), 
            pokeTuple(name='Barbaracle', id=689, type=['rock', 'water']), 
            pokeTuple(name='Skrelp', id=690, type=['poison', 'water']), 
            pokeTuple(name='Dragalge', id=691, type=['poison', 'dragon']), 
            pokeTuple(name='Clauncher', id=692, type=['water']), 
            pokeTuple(name='Clawitzer', id=693, type=['water']), 
            pokeTuple(name='Helioptile', id=694, type=['electric', 'normal']), 
            pokeTuple(name='Heliolisk', id=695, type=['electric', 'normal']), 
            pokeTuple(name='Tyrunt', id=696, type=['rock', 'dragon']), 
            pokeTuple(name='Tyrantrum', id=697, type=['rock', 'dragon']), 
            pokeTuple(name='Amaura', id=698, type=['rock', 'ice']), 
            pokeTuple(name='Aurorus', id=699, type=['rock', 'ice']), 
            pokeTuple(name='Sylveon', id=700, type=['fairy']), 
            pokeTuple(name='Hawlucha', id=701, type=['fighting', 'flying']), 
            pokeTuple(name='Dedenne', id=702, type=['electric', 'fairy']), 
            pokeTuple(name='Carbink', id=703, type=['rock', 'fairy']), 
            pokeTuple(name='Goomy', id=704, type=['dragon']), 
            pokeTuple(name='Sliggoo', id=705, type=['dragon']), 
            pokeTuple(name='Goodra', id=706, type=['dragon']), 
            pokeTuple(name='Klefki', id=707, type=['steel', 'fairy']), 
            pokeTuple(name='Phantump', id=708, type=['ghost', 'grass']), 
            pokeTuple(name='Trevenant', id=709, type=['ghost', 'grass']), 
            pokeTuple(name='Bergmite', id=712, type=['ice']), 
            pokeTuple(name='Avalugg', id=713, type=['ice']), 
            pokeTuple(name='Noibat', id=714, type=['flying', 'dragon']), 
            pokeTuple(name='Noivern', id=715, type=['flying', 'dragon']), 
            pokeTuple(name='Xerneas', id=716, type=['fairy']), 
            pokeTuple(name='Yveltal', id=717, type=['dark', 'flying']), 
            pokeTuple(name='Diancie', id=719, type=['rock', 'fairy']), 
            pokeTuple(name='Hoopa', id=720, type=['psychic', 'ghost']), 
            pokeTuple(name='Volcanion', id=721, type=['fire', 'water']), 
            pokeTuple(name='Rowlet', id=722, type=['grass', 'flying']), 
            pokeTuple(name='Dartrix', id=723, type=['grass', 'flying']), 
            pokeTuple(name='Decidueye', id=724, type=['grass', 'ghost']), 
            pokeTuple(name='Litten', id=725, type=['fire']), 
            pokeTuple(name='Torracat', id=726, type=['fire']), 
            pokeTuple(name='Incineroar', id=727, type=['fire', 'dark']), 
            pokeTuple(name='Popplio', id=728, type=['water']), 
            pokeTuple(name='Brionne', id=729, type=['water']), 
            pokeTuple(name='Primarina', id=730, type=['water', 'fairy']), 
            pokeTuple(name='Pikipek', id=731, type=['normal', 'flying']), 
            pokeTuple(name='Trumbeak', id=732, type=['normal', 'flying']), 
            pokeTuple(name='Toucannon', id=733, type=['normal', 'flying']), 
            pokeTuple(name='Yungoos', id=734, type=['normal']), 
            pokeTuple(name='Gumshoos', id=735, type=['normal']), 
            pokeTuple(name='Grubbin', id=736, type=['bug']), 
            pokeTuple(name='Charjabug', id=737, type=['bug', 'electric']), 
            pokeTuple(name='Vikavolt', id=738, type=['bug', 'electric']), 
            pokeTuple(name='Crabrawler', id=739, type=['fighting']), 
            pokeTuple(name='Crabominable', id=740, type=['fighting', 'ice']), 
            pokeTuple(name='Cutiefly', id=742, type=['bug', 'fairy']), 
            pokeTuple(name='Ribombee', id=743, type=['bug', 'fairy']), 
            pokeTuple(name='Rockruff', id=744, type=['rock']), 
            pokeTuple(name='Mareanie', id=747, type=['poison', 'water']), 
            pokeTuple(name='Toxapex', id=748, type=['poison', 'water']), 
            pokeTuple(name='Mudbray', id=749, type=['ground']), 
            pokeTuple(name='Mudsdale', id=750, type=['ground']), 
            pokeTuple(name='Dewpider', id=751, type=['water', 'bug']), 
            pokeTuple(name='Araquanid', id=752, type=['water', 'bug']), 
            pokeTuple(name='Fomantis', id=753, type=['grass']), 
            pokeTuple(name='Lurantis', id=754, type=['grass']), 
            pokeTuple(name='Morelull', id=755, type=['grass', 'fairy']), 
            pokeTuple(name='Shiinotic', id=756, type=['grass', 'fairy']), 
            pokeTuple(name='Salandit', id=757, type=['poison', 'fire']), 
            pokeTuple(name='Salazzle', id=758, type=['poison', 'fire']), 
            pokeTuple(name='Stufful', id=759, type=['normal', 'fighting']), 
            pokeTuple(name='Bewear', id=760, type=['normal', 'fighting']), 
            pokeTuple(name='Bounsweet', id=761, type=['grass']), 
            pokeTuple(name='Steenee', id=762, type=['grass']), 
            pokeTuple(name='Tsareena', id=763, type=['grass']), 
            pokeTuple(name='Comfey', id=764, type=['fairy']), 
            pokeTuple(name='Oranguru', id=765, type=['normal', 'psychic']), 
            pokeTuple(name='Passimian', id=766, type=['fighting']), 
            pokeTuple(name='Wimpod', id=767, type=['bug', 'water']), 
            pokeTuple(name='Golisopod', id=768, type=['bug', 'water']), 
            pokeTuple(name='Sandygast', id=769, type=['ghost', 'ground']), 
            pokeTuple(name='Palossand', id=770, type=['ghost', 'ground']), 
            pokeTuple(name='Pyukumuku', id=771, type=['water']), 
            pokeTuple(name='Silvally', id=773, type=['normal']), 
            pokeTuple(name='Komala', id=775, type=['normal']), 
            pokeTuple(name='Turtonator', id=776, type=['fire', 'dragon']), 
            pokeTuple(name='Togedemaru', id=777, type=['electric', 'steel']), 
            pokeTuple(name='Bruxish', id=779, type=['water', 'psychic']), 
            pokeTuple(name='Drampa', id=780, type=['normal', 'dragon']), 
            pokeTuple(name='Dhelmise', id=781, type=['ghost', 'grass']), 
            pokeTuple(name='Cosmog', id=789, type=['psychic']), 
            pokeTuple(name='Cosmoem', id=790, type=['psychic']), 
            pokeTuple(name='Solgaleo', id=791, type=['psychic', 'steel']), 
            pokeTuple(name='Lunala', id=792, type=['psychic', 'ghost']), 
            pokeTuple(name='Nihilego', id=793, type=['rock', 'poison']), 
            pokeTuple(name='Buzzwole', id=794, type=['bug', 'fighting']), 
            pokeTuple(name='Pheromosa', id=795, type=['bug', 'fighting']), 
            pokeTuple(name='Xurkitree', id=796, type=['electric']), 
            pokeTuple(name='Celesteela', id=797, type=['steel', 'flying']), 
            pokeTuple(name='Kartana', id=798, type=['grass', 'steel']), 
            pokeTuple(name='Guzzlord', id=799, type=['dark', 'dragon']), 
            pokeTuple(name='Necrozma', id=800, type=['psychic']), 
            pokeTuple(name='Magearna', id=801, type=['steel', 'fairy']), 
            pokeTuple(name='Marshadow', id=802, type=['fighting', 'ghost']), 
            pokeTuple(name='Poipole', id=803, type=['poison']), 
            pokeTuple(name='Naganadel', id=804, type=['poison', 'dragon']), 
            pokeTuple(name='Stakataka', id=805, type=['rock', 'steel']), 
            pokeTuple(name='Blacephalon', id=806, type=['fire', 'ghost']), 
            pokeTuple(name='Zeraora', id=807, type=['electric']), 
            pokeTuple(name='Meltan', id=808, type=['steel']), 
            pokeTuple(name='Melmetal', id=809, type=['steel']), 
            pokeTuple(name='Grookey', id=810, type=['grass']), 
            pokeTuple(name='Thwackey', id=811, type=['grass']), 
            pokeTuple(name='Rillaboom', id=812, type=['grass']), 
            pokeTuple(name='Scorbunny', id=813, type=['fire']), 
            pokeTuple(name='Raboot', id=814, type=['fire']), 
            pokeTuple(name='Cinderace', id=815, type=['fire']), 
            pokeTuple(name='Sobble', id=816, type=['water']), 
            pokeTuple(name='Drizzile', id=817, type=['water']), 
            pokeTuple(name='Inteleon', id=818, type=['water']), 
            pokeTuple(name='Skwovet', id=819, type=['normal']), 
            pokeTuple(name='Greedent', id=820, type=['normal']), 
            pokeTuple(name='Rookidee', id=821, type=['flying']), 
            pokeTuple(name='Corvisquire', id=822, type=['flying']), 
            pokeTuple(name='Corviknight', id=823, type=['flying', 'steel']), 
            pokeTuple(name='Blipbug', id=824, type=['bug']), 
            pokeTuple(name='Dottler', id=825, type=['bug', 'psychic']), 
            pokeTuple(name='Orbeetle', id=826, type=['bug', 'psychic']), 
            pokeTuple(name='Nickit', id=827, type=['dark']), 
            pokeTuple(name='Thievul', id=828, type=['dark']), 
            pokeTuple(name='Gossifleur', id=829, type=['grass']), 
            pokeTuple(name='Eldegoss', id=830, type=['grass']), 
            pokeTuple(name='Wooloo', id=831, type=['normal']), 
            pokeTuple(name='Dubwool', id=832, type=['normal']), 
            pokeTuple(name='Chewtle', id=833, type=['water']), 
            pokeTuple(name='Drednaw', id=834, type=['water', 'rock']), 
            pokeTuple(name='Yamper', id=835, type=['electric']), 
            pokeTuple(name='Boltund', id=836, type=['electric']), 
            pokeTuple(name='Rolycoly', id=837, type=['rock']), 
            pokeTuple(name='Carkol', id=838, type=['rock', 'fire']), 
            pokeTuple(name='Coalossal', id=839, type=['rock', 'fire']), 
            pokeTuple(name='Applin', id=840, type=['grass', 'dragon']), 
            pokeTuple(name='Flapple', id=841, type=['grass', 'dragon']), 
            pokeTuple(name='Appletun', id=842, type=['grass', 'dragon']), 
            pokeTuple(name='Silicobra', id=843, type=['ground']), 
            pokeTuple(name='Sandaconda', id=844, type=['ground']), 
            pokeTuple(name='Cramorant', id=845, type=['flying', 'water']), 
            pokeTuple(name='Arrokuda', id=846, type=['water']), 
            pokeTuple(name='Barraskewda', id=847, type=['water']), 
            pokeTuple(name='Toxel', id=848, type=['electric', 'poison']), 
            pokeTuple(name='Sizzlipede', id=850, type=['fire', 'bug']), 
            pokeTuple(name='Centiskorch', id=851, type=['fire', 'bug']), 
            pokeTuple(name='Clobbopus', id=852, type=['fighting']), 
            pokeTuple(name='Grapploct', id=853, type=['fighting']), 
            pokeTuple(name='Sinistea', id=854, type=['ghost']), 
            pokeTuple(name='Polteageist', id=855, type=['ghost']), 
            pokeTuple(name='Hatenna', id=856, type=['psychic']), 
            pokeTuple(name='Hattrem', id=857, type=['psychic']), 
            pokeTuple(name='Hatterene', id=858, type=['psychic', 'fairy']), 
            pokeTuple(name='Impidimp', id=859, type=['dark', 'fairy']), 
            pokeTuple(name='Morgrem', id=860, type=['dark', 'fairy']), 
            pokeTuple(name='Grimmsnarl', id=861, type=['dark', 'fairy']), 
            pokeTuple(name='Obstagoon', id=862, type=['dark', 'normal']), 
            pokeTuple(name='Perrserker', id=863, type=['steel']), 
            pokeTuple(name='Cursola', id=864, type=['ghost']), 
            pokeTuple(name='Sirfetchd', id=865, type=['fighting']), 
            pokeTuple(name='Runerigus', id=867, type=['ground', 'ghost']), 
            pokeTuple(name='Milcery', id=868, type=['fairy']), 
            pokeTuple(name='Alcremie', id=869, type=['fairy']), 
            pokeTuple(name='Falinks', id=870, type=['fighting']), 
            pokeTuple(name='Pincurchin', id=871, type=['electric']), 
            pokeTuple(name='Snom', id=872, type=['ice', 'bug']), 
            pokeTuple(name='Frosmoth', id=873, type=['ice', 'bug']), 
            pokeTuple(name='Stonjourner', id=874, type=['rock']), 
            pokeTuple(name='Cufant', id=878, type=['steel']), 
            pokeTuple(name='Copperajah', id=879, type=['steel']), 
            pokeTuple(name='Dracozolt', id=880, type=['electric', 'dragon']), 
            pokeTuple(name='Arctozolt', id=881, type=['electric', 'ice']), 
            pokeTuple(name='Dracovish', id=882, type=['water', 'dragon']), 
            pokeTuple(name='Arctovish', id=883, type=['water', 'ice']), 
            pokeTuple(name='Duraludon', id=884, type=['steel', 'dragon']), 
            pokeTuple(name='Dreepy', id=885, type=['dragon', 'ghost']), 
            pokeTuple(name='Drakloak', id=886, type=['dragon', 'ghost']), 
            pokeTuple(name='Dragapult', id=887, type=['dragon', 'ghost']), 
            pokeTuple(name='Zacian', id=888, type=['fairy']), 
            pokeTuple(name='Zamazenta', id=889, type=['fighting']), 
            pokeTuple(name='Eternatus', id=890, type=['poison', 'dragon']), 
            pokeTuple(name='Kubfu', id=891, type=['fighting']), 
            pokeTuple(name='Zarude', id=893, type=['dark', 'grass']), 
            pokeTuple(name='Regieleki', id=894, type=['electric']), 
            pokeTuple(name='Regidrago', id=895, type=['dragon']), 
            pokeTuple(name='Glastrier', id=896, type=['ice']), 
            pokeTuple(name='Spectrier', id=897, type=['ghost']), 
            pokeTuple(name='Calyrex', id=898, type=['psychic', 'grass'])
            ]
    
    def getNameList(self, how="low"):
        if how == "low":
            return [str(i.name).lower() for i in self.me]
        elif how == "title":
            return [i.name for i in self.me]
        else:
            return "Error"
    
    def getType(self, name: str):
        for i in self.me:
            if i.name == name.lower().title():
                return i.type